const stormModes14={flash:{title:"先看到亮光",text:"閃電是亮亮的光，所以我們常常會先用眼睛看到它。",remember:"閃電是光，雷是聲音。",meter:"72%",label:"一下就注意到",bolt:1,sound:.12},sound:{title:"再聽到雷聲",text:"雷是轟隆轟隆的聲音，所以我們是用耳朵聽到它。",remember:"亮的是閃電，聽到的是雷。",meter:"86%",label:"很大聲",bolt:.18,sound:1},both:{title:"兩個一起記",text:"打雷天最常一起記住的，就是先看到閃電，再聽到雷聲。",remember:"很多時候是先看到亮，再聽到聲音。",meter:"100%",label:"一起記住",bolt:1,sound:1}};
const s14Buttons=document.querySelectorAll(".mode-button"),s14Title=document.getElementById("mode-title"),s14Text=document.getElementById("mode-text"),s14Remember=document.getElementById("mode-remember"),s14Meter=document.getElementById("storm-meter"),s14Label=document.getElementById("storm-label"),s14Bolt=document.querySelector(".stage-bolt"),s14Sound=document.querySelector(".stage-sound");
function setStormMode14(k){const m=stormModes14[k];if(!m)return;s14Buttons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));s14Title.textContent=m.title;s14Text.textContent=m.text;s14Remember.textContent=m.remember;s14Meter.style.width=m.meter;s14Label.textContent=m.label;s14Bolt.style.opacity=String(m.bolt);s14Sound.style.opacity=String(m.sound);}
s14Buttons.forEach(b=>b.addEventListener("click",()=>setStormMode14(b.dataset.mode)));
const quizData14=[{question:"閃電最接近下面哪種說法？",options:["亮亮的光","轟隆聲","冷冷的風"],answer:0,explanation:"答對了。閃電是亮亮的光。"},
{question:"雷最接近下面哪種說法？",options:["轟隆的聲音","天空裡的彩虹","地上的水坑"],answer:0,explanation:"對。雷是轟隆轟隆的聲音。"},
{question:"很多時候我們會先怎樣？",options:["先看到亮，再聽到聲音","先聽到彩虹","先看到風"],answer:0,explanation:"沒錯。很多時候會先看到亮，再聽到雷聲。"},
{question:"打雷閃電時比較安全的做法是什麼？",options:["先到室內","跑去空地看","去水邊玩"],answer:0,explanation:"答對了。打雷閃電時先到室內比較安全。"},
{question:"第十四課最重要的重點是什麼？",options:["閃電是光，雷是聲音","雷和閃電一模一樣","打雷天不用注意"],answer:0,explanation:"對。這就是本課最重要的觀念。"}];
const qp14=document.getElementById("quiz-progress"),qq14=document.getElementById("quiz-question"),qo14=document.getElementById("quiz-options"),qf14=document.getElementById("quiz-feedback"),qn14=document.getElementById("quiz-next");let qi14=0,ql14=false;function renderQuiz14(){const item=quizData14[qi14];ql14=false;qp14.textContent=`第 ${qi14+1} 題，共 ${quizData14.length} 題`;qq14.textContent=item.question;qf14.textContent="";qn14.hidden=true;qo14.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer14(index));qo14.appendChild(button);});}function handleAnswer14(selectedIndex){if(ql14)return;ql14=true;const item=quizData14[qi14];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf14.textContent=item.explanation;qn14.hidden=false;qn14.textContent=qi14===quizData14.length-1?"再玩一次":"下一題 →";}qn14.addEventListener("click",()=>{qi14=qi14===quizData14.length-1?0:qi14+1;renderQuiz14();});setStormMode14("flash");renderQuiz14();
