const rainThunderModes15={cloud:{title:"只有大雲",text:"有些雲會越長越高、越長越厚，這種雲比較容易變成會帶來很多天氣變化的雲。",remember:"打雷和下雨常一起，是因為它們常來自同一種大雲。",meter:"42%",label:"開始變明顯",bolt:.18,rain:.12},rain:{title:"開始下雨",text:"當這種大雲開始下雨時，天空通常也會變得更暗、更有變化。",remember:"很多時候是先看到雲變厚，再開始下雨。",meter:"72%",label:"雨變明顯",bolt:.18,rain:1},storm:{title:"雷和雨一起",text:"如果這種大雲也帶來閃電和雷聲，就會變成我們常說的雷雨天。",remember:"雷雨天常常是大雲、雨和雷一起出現。",meter:"100%",label:"雷雨一起",bolt:1,rain:1}};
const r15Buttons=document.querySelectorAll(".mode-button"),r15Title=document.getElementById("mode-title"),r15Text=document.getElementById("mode-text"),r15Remember=document.getElementById("mode-remember"),r15Meter=document.getElementById("meter"),r15Label=document.getElementById("meter-label"),r15Bolt=document.querySelector(".stage-bolt"),r15Rain=document.querySelector(".stage-rain");
function setRainThunderMode15(k){const m=rainThunderModes15[k];if(!m)return;r15Buttons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));r15Title.textContent=m.title;r15Text.textContent=m.text;r15Remember.textContent=m.remember;r15Meter.style.width=m.meter;r15Label.textContent=m.label;r15Bolt.style.opacity=String(m.bolt);r15Rain.style.opacity=String(m.rain);}
r15Buttons.forEach(b=>b.addEventListener("click",()=>setRainThunderMode15(b.dataset.mode)));
const quizData15=[{question:"為什麼打雷常常會和下雨一起？",options:["因為它們常來自同一種大雷雨雲","因為彩虹把它們綁在一起","因為地面把它們推出來"],answer:0,explanation:"答對了。打雷和下雨常常來自同一種大雷雨雲。"},
{question:"大一點、厚一點的雲，常常先帶來什麼變化？",options:["雲變厚、天空變暗、可能開始下雨","月亮變近","草地變白"],answer:0,explanation:"對。常常會先看到雲變厚、天空變暗。"},
{question:"雷雨天最接近下面哪種情況？",options:["大雲、下雨、打雷一起來","只有風沒有雲","只有彩虹沒有雨"],answer:0,explanation:"沒錯。雷雨天最常是大雲、下雨、打雷一起來。"},
{question:"遇到雷雨時比較好的做法是什麼？",options:["先進室內","跑去空地看","去水邊站著"],answer:0,explanation:"答對了。雷雨時先進室內比較安全。"},
{question:"第十五課最重要的重點是什麼？",options:["打雷和下雨常常來自同一種大雲","雷和雨完全沒關係","只有晚上才會打雷"],answer:0,explanation:"對。這就是本課的重點。"}];
const qp15=document.getElementById("quiz-progress"),qq15=document.getElementById("quiz-question"),qo15=document.getElementById("quiz-options"),qf15=document.getElementById("quiz-feedback"),qn15=document.getElementById("quiz-next");let qi15=0,ql15=false;function renderQuiz15(){const item=quizData15[qi15];ql15=false;qp15.textContent=`第 ${qi15+1} 題，共 ${quizData15.length} 題`;qq15.textContent=item.question;qf15.textContent="";qn15.hidden=true;qo15.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer15(index));qo15.appendChild(button);});}function handleAnswer15(selectedIndex){if(ql15)return;ql15=true;const item=quizData15[qi15];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf15.textContent=item.explanation;qn15.hidden=false;qn15.textContent=qi15===quizData15.length-1?"再玩一次":"下一題 →";}qn15.addEventListener("click",()=>{qi15=qi15===quizData15.length-1?0:qi15+1;renderQuiz15();});setRainThunderMode15("cloud");renderQuiz15();
