const dewModes18={day:{title:"白天",text:"白天比較暖時，葉子上不一定看得到露水。",remember:"露水常常出現在清晨，比較涼的時候。",meter:"18%",label:"比較少",dew:.08},cool:{title:"晚上變涼",text:"晚上和清晨比較涼時，葉子表面更容易慢慢出現小水珠。",remember:"變涼之後，比較容易開始有露水。",meter:"58%",label:"開始有機會",dew:.42},dew:{title:"清晨露水",text:"到了清晨，你就可能在草地、葉子和車子表面看到一顆一顆小水珠。",remember:"清晨看到的小水珠，常常就是露水。",meter:"100%",label:"看到了",dew:1}};
const d18Buttons=document.querySelectorAll(".mode-button"),d18Title=document.getElementById("mode-title"),d18Text=document.getElementById("mode-text"),d18Remember=document.getElementById("mode-remember"),d18Meter=document.getElementById("meter"),d18Label=document.getElementById("meter-label"),d18Drops=document.querySelectorAll(".stage-dew");
function setDewMode18(k){const m=dewModes18[k];if(!m)return;d18Buttons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));d18Title.textContent=m.title;d18Text.textContent=m.text;d18Remember.textContent=m.remember;d18Meter.style.width=m.meter;d18Label.textContent=m.label;d18Drops.forEach(drop=>drop.style.opacity=String(m.dew));}
d18Buttons.forEach(b=>b.addEventListener("click",()=>setDewMode18(b.dataset.mode)));
const quizData18=[{question:"露水最常在哪個時間比較容易看到？",options:["清晨比較涼的時候","正中午最熱的時候","只有下雪時"],answer:0,explanation:"答對了。露水常常在清晨比較容易看到。"},
{question:"露水最接近下面哪種樣子？",options:["葉子上的一顆一顆小水珠","天上的彩虹","地上的大水坑"],answer:0,explanation:"對。露水最常看到的樣子就是一顆一顆小水珠。"},
{question:"露水常常會出現在什麼地方？",options:["葉子、草地、車子表面","只有雲裡","只有海底"],answer:0,explanation:"沒錯。露水常常出現在比較涼的表面上。"},
{question:"露水出現和什麼感覺很有關？",options:["晚上和清晨比較涼","下午比較熱","一定有打雷"],answer:0,explanation:"答對了。露水和比較涼的感覺很有關。"},
{question:"第十八課最重要的重點是什麼？",options:["露水常是清晨表面上的小水珠","露水就是下雨","露水和水沒有關係"],answer:0,explanation:"對。這就是本課最重要的重點。"}];
const qp18=document.getElementById("quiz-progress"),qq18=document.getElementById("quiz-question"),qo18=document.getElementById("quiz-options"),qf18=document.getElementById("quiz-feedback"),qn18=document.getElementById("quiz-next");let qi18=0,ql18=false;function renderQuiz18(){const item=quizData18[qi18];ql18=false;qp18.textContent=`第 ${qi18+1} 題，共 ${quizData18.length} 題`;qq18.textContent=item.question;qf18.textContent="";qn18.hidden=true;qo18.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer18(index));qo18.appendChild(button);});}function handleAnswer18(selectedIndex){if(ql18)return;ql18=true;const item=quizData18[qi18];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf18.textContent=item.explanation;qn18.hidden=false;qn18.textContent=qi18===quizData18.length-1?"再玩一次":"下一題 →";}qn18.addEventListener("click",()=>{qi18=qi18===quizData18.length-1?0:qi18+1;renderQuiz18();});setDewMode18("day");renderQuiz18();
