const windStrengthModes={calm:{title:"幾乎沒風",text:"空氣動得很少，所以旗子和樹葉也不太動。",remember:"風越大，通常越容易看到東西被吹動。",meter:"8%",label:"很少",wind:.08,flag:"0deg"},breeze:{title:"微風",text:"有一點點風時，旗子會輕輕飄，樹葉也會輕輕動。",remember:"微風常常是『有感覺，但還不會吹很大』。",meter:"34%",label:"微微的",wind:.36,flag:"8deg"},windy:{title:"比較有風",text:"風更明顯時，旗子會拉得更開，樹葉和頭髮也更容易動。",remember:"東西動得越明顯，通常風也越明顯。",meter:"68%",label:"明顯了",wind:.74,flag:"18deg"},strong:{title:"強風",text:"強風時，很多東西都會被吹得很明顯，外出也要更注意安全。",remember:"強風不是只有『大一點』，而是會讓很多東西都明顯改變。",meter:"100%",label:"很大",wind:1,flag:"28deg"}};
const wsButtons=document.querySelectorAll(".mode-button"),wsTitle=document.getElementById("mode-title"),wsText=document.getElementById("mode-text"),wsRemember=document.getElementById("mode-remember"),wsMeter=document.getElementById("wind-meter"),wsLabel=document.getElementById("wind-label"),wsWind=document.querySelector(".stage-wind"),wsFlag=document.querySelector(".stage-flag");
function setWindStrengthMode(k){const m=windStrengthModes[k];if(!m)return;wsButtons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));wsTitle.textContent=m.title;wsText.textContent=m.text;wsRemember.textContent=m.remember;wsMeter.style.width=m.meter;wsLabel.textContent=m.label;wsWind.style.opacity=String(m.wind);wsFlag.style.transform=`rotate(${m.flag})`;}
wsButtons.forEach(b=>b.addEventListener("click",()=>setWindStrengthMode(b.dataset.mode)));
document.querySelectorAll(".game-card").forEach(card=>{const answer=card.dataset.answer,buttons=card.querySelectorAll("button"),feedback=card.querySelector(".game-feedback");buttons.forEach(button=>button.addEventListener("click",()=>{buttons.forEach(item=>{item.disabled=true;item.classList.remove("is-correct","is-wrong")});buttons.forEach(item=>{if(item.textContent===answer)item.classList.add("is-correct")});if(button.textContent!==answer){button.classList.add("is-wrong");feedback.textContent=`這題比較像${answer}，因為描述的動作和感覺最接近${answer}。`;}else feedback.textContent=`答對了，這題就是${answer}。`;}));});
const quizData11=[{question:"旗子和樹葉都幾乎不動，比較像哪種情況？",options:["幾乎沒風","強風","颱風"],answer:0,explanation:"答對了。東西都不太動時，通常表示幾乎沒風。"},
{question:"風變大時，下面哪件事最常一起變明顯？",options:["旗子和樹葉的動作","月亮的大小","牆壁的位置"],answer:0,explanation:"對。風變大時，最常看到旗子和樹葉動得更明顯。"},
{question:"微風最接近下面哪種感覺？",options:["有一點感覺，但不會吹很大","東西全部亂飛","完全沒感覺"],answer:0,explanation:"沒錯。微風是有感覺，但不會太強。"},
{question:"強風時要更注意什麼？",options:["外出安全", "只要看雲形", "一定會下雪"],answer:0,explanation:"答對了。強風時外出和周圍東西都要更注意。"},
{question:"第十一課最重要的重點是什麼？",options:["用生活線索分辨風大風小","只靠猜風力","風力看不出來"],answer:0,explanation:"對。這課重點就是用生活線索判斷風力。"}];
const qp11=document.getElementById("quiz-progress"),qq11=document.getElementById("quiz-question"),qo11=document.getElementById("quiz-options"),qf11=document.getElementById("quiz-feedback"),qn11=document.getElementById("quiz-next");let qi11=0,ql11=false;
function renderQuiz11(){const item=quizData11[qi11];ql11=false;qp11.textContent=`第 ${qi11+1} 題，共 ${quizData11.length} 題`;qq11.textContent=item.question;qf11.textContent="";qn11.hidden=true;qo11.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer11(index));qo11.appendChild(button);});}
function handleAnswer11(selectedIndex){if(ql11)return;ql11=true;const item=quizData11[qi11];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf11.textContent=item.explanation;qn11.hidden=false;qn11.textContent=qi11===quizData11.length-1?"再玩一次":"下一題 →";}
qn11.addEventListener("click",()=>{qi11=qi11===quizData11.length-1?0:qi11+1;renderQuiz11();});setWindStrengthMode("calm");renderQuiz11();
