const fogModes17={clear:{title:"沒有霧",text:"沒有霧時，前面的東西通常比較清楚。",remember:"霧很像低低貼近地面的雲。",meter:"100%",label:"很清楚",fog1:.04,fog2:.02},light:{title:"薄霧",text:"有一點霧時，前面還看得到，但會開始有白白的感覺。",remember:"霧一變多，前面的東西就會變得比較不清楚。",meter:"62%",label:"有點模糊",fog1:.32,fog2:.18},thick:{title:"濃霧",text:"霧很多時，前面的路和東西都會更不清楚。",remember:"霧最明顯的感覺，就是看不清楚前面。",meter:"22%",label:"很不清楚",fog1:.74,fog2:.54}};
const fg17Buttons=document.querySelectorAll(".mode-button"),fg17Title=document.getElementById("mode-title"),fg17Text=document.getElementById("mode-text"),fg17Remember=document.getElementById("mode-remember"),fg17Meter=document.getElementById("meter"),fg17Label=document.getElementById("meter-label"),fg17Fog1=document.querySelector(".stage-fog.one"),fg17Fog2=document.querySelector(".stage-fog.two");
function setFogMode17(k){const m=fogModes17[k];if(!m)return;fg17Buttons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));fg17Title.textContent=m.title;fg17Text.textContent=m.text;fg17Remember.textContent=m.remember;fg17Meter.style.width=m.meter;fg17Label.textContent=m.label;fg17Fog1.style.opacity=String(m.fog1);fg17Fog2.style.opacity=String(m.fog2);}
fg17Buttons.forEach(b=>b.addEventListener("click",()=>setFogMode17(b.dataset.mode)));
const quizData17=[{question:"霧最像下面哪種說法？",options:["低低貼近地面的雲","高高在宇宙的冰","彩虹掉下來"],answer:0,explanation:"答對了。霧很像低低貼近地面的雲。"},
{question:"霧最明顯的生活感覺是什麼？",options:["前面看不太清楚","天空變很熱","東西都變紅色"],answer:0,explanation:"對。霧最明顯的感覺就是看不太清楚。"},
{question:"霧越多時，通常會怎樣？",options:["前面的東西更不清楚","每樣東西更亮","一定會打雷"],answer:0,explanation:"沒錯。霧越多，通常就越不清楚。"},
{question:"霧大時比較好的做法是什麼？",options:["慢一點、先看清楚再走","往看不見的地方衝","自己亂跑"],answer:0,explanation:"答對了。霧大時要更小心。"},
{question:"第十七課最重要的重點是什麼？",options:["霧像低低的雲，會讓人看不清楚","霧是地上的沙子","霧和水沒有關係"],answer:0,explanation:"對。這就是本課最重要的重點。"}];
const qp17=document.getElementById("quiz-progress"),qq17=document.getElementById("quiz-question"),qo17=document.getElementById("quiz-options"),qf17=document.getElementById("quiz-feedback"),qn17=document.getElementById("quiz-next");let qi17=0,ql17=false;function renderQuiz17(){const item=quizData17[qi17];ql17=false;qp17.textContent=`第 ${qi17+1} 題，共 ${quizData17.length} 題`;qq17.textContent=item.question;qf17.textContent="";qn17.hidden=true;qo17.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer17(index));qo17.appendChild(button);});}function handleAnswer17(selectedIndex){if(ql17)return;ql17=true;const item=quizData17[qi17];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf17.textContent=item.explanation;qn17.hidden=false;qn17.textContent=qi17===quizData17.length-1?"再玩一次":"下一題 →";}qn17.addEventListener("click",()=>{qi17=qi17===quizData17.length-1?0:qi17+1;renderQuiz17();});setFogMode17("clear");renderQuiz17();
