const typhoonLifeModes={before:{title:"還沒到",text:"颱風還沒真的影響時，生活看起來可能還很平常，但就要開始注意消息。",remember:"颱風天最重要的是先注意、提早準備、待在安全的地方。",meter:"28%",label:"先注意",wind:.08,rain:.06},wind:{title:"風變大",text:"颱風靠近時，常常先感覺到風變得比較大，外面的東西也更容易動。",remember:"風一變大，就表示要更小心。",meter:"64%",label:"更注意",wind:.82,rain:.18},rain:{title:"雨變大",text:"颱風天常常不只是風，雨也會越來越明顯，地面更容易很快變濕。",remember:"颱風常常是風大加上雨大一起來。",meter:"82%",label:"很要注意",wind:.42,rain:1}, "stay-safe":{title:"待在室內",text:"風雨明顯時，待在室內通常比較安全，也要跟著家裡和學校的安排。",remember:"颱風天安全第一，先待在安全的地方。",meter:"100%",label:"最需要小心",wind:.54,rain:.82}};
const tlButtons=document.querySelectorAll(".mode-button"),tlTitle=document.getElementById("mode-title"),tlText=document.getElementById("mode-text"),tlRemember=document.getElementById("mode-remember"),tlMeter=document.getElementById("care-meter"),tlLabel=document.getElementById("care-label"),tlWind=document.querySelector(".stage-wind"),tlRain=document.querySelector(".stage-rain");
function setTyphoonLifeMode(k){const m=typhoonLifeModes[k];if(!m)return;tlButtons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));tlTitle.textContent=m.title;tlText.textContent=m.text;tlRemember.textContent=m.remember;tlMeter.style.width=m.meter;tlLabel.textContent=m.label;tlWind.style.opacity=String(m.wind);tlRain.style.opacity=String(m.rain);}
tlButtons.forEach(b=>b.addEventListener("click",()=>setTyphoonLifeMode(b.dataset.mode)));
const quizData13=[{question:"颱風來時，下面哪件事最常變明顯？",options:["風和雨","太陽更亮","月亮更近"],answer:0,explanation:"答對了。颱風來時，最常明顯的是風和雨。"},
{question:"颱風天通常比較安全的做法是什麼？",options:["待在室內","到外面追風","跑去積水旁邊看"],answer:0,explanation:"對。颱風天待在室內通常比較安全。"},
{question:"颱風還沒真的影響時，先做什麼比較好？",options:["先注意消息和提醒","完全不用管","去海邊玩"],answer:0,explanation:"沒錯。先注意消息和提醒最重要。"},
{question:"颱風天為什麼要看大人和學校的安排？",options:["因為安全最重要","因為一定會下雪","因為風會消失"],answer:0,explanation:"答對了。颱風天最優先的是安全。"},
{question:"第十三課最重要的重點是什麼？",options:["颱風來時要注意、提早準備、待在安全地方","颱風天和平常完全一樣","只要看雲就好"],answer:0,explanation:"對。這就是本課最重要的重點。"}];
const qp13=document.getElementById("quiz-progress"),qq13=document.getElementById("quiz-question"),qo13=document.getElementById("quiz-options"),qf13=document.getElementById("quiz-feedback"),qn13=document.getElementById("quiz-next");let qi13=0,ql13=false;
function renderQuiz13(){const item=quizData13[qi13];ql13=false;qp13.textContent=`第 ${qi13+1} 題，共 ${quizData13.length} 題`;qq13.textContent=item.question;qf13.textContent="";qn13.hidden=true;qo13.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer13(index));qo13.appendChild(button);});}
function handleAnswer13(selectedIndex){if(ql13)return;ql13=true;const item=quizData13[qi13];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf13.textContent=item.explanation;qn13.hidden=false;qn13.textContent=qi13===quizData13.length-1?"再玩一次":"下一題 →";}
qn13.addEventListener("click",()=>{qi13=qi13===quizData13.length-1?0:qi13+1;renderQuiz13();});setTyphoonLifeMode("before");renderQuiz13();
