const rainbowModes16={sun:{title:"只有太陽",text:"只有太陽時，天空可以很亮，可是不一定會有彩虹。",remember:"彩虹常常需要太陽和小水滴一起出現。",meter:"22%",label:"還不夠",drops:.1,rainbow:.06},drops:{title:"太陽和水滴",text:"如果空氣裡有很多小水滴，像雨後那樣，看到彩虹的機會就比較高。",remember:"彩虹和陽光、小水滴很有關係。",meter:"68%",label:"有機會了",drops:1,rainbow:.18},rainbow:{title:"彩虹出現",text:"當太陽、小水滴和角度都剛好時，我們就可能看到彎彎的彩虹。",remember:"有太陽、有小水滴、角度剛好，才比較容易看到彩虹。",meter:"100%",label:"看到了",drops:1,rainbow:1}};
const rb16Buttons=document.querySelectorAll(".mode-button"),rb16Title=document.getElementById("mode-title"),rb16Text=document.getElementById("mode-text"),rb16Remember=document.getElementById("mode-remember"),rb16Meter=document.getElementById("meter"),rb16Label=document.getElementById("meter-label"),rb16Drops=document.querySelector(".stage-drops"),rb16Rainbow=document.querySelector(".stage-rainbow");
function setRainbowMode16(k){const m=rainbowModes16[k];if(!m)return;rb16Buttons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));rb16Title.textContent=m.title;rb16Text.textContent=m.text;rb16Remember.textContent=m.remember;rb16Meter.style.width=m.meter;rb16Label.textContent=m.label;rb16Drops.style.opacity=String(m.drops);rb16Rainbow.style.opacity=String(m.rainbow);}
rb16Buttons.forEach(b=>b.addEventListener("click",()=>setRainbowMode16(b.dataset.mode)));
const quizData16=[{question:"彩虹常常和哪兩樣東西很有關？",options:["太陽和小水滴","雷和風","雪和冰"],answer:0,explanation:"答對了。彩虹常常和太陽、小水滴很有關。"},
{question:"是不是每次下雨都一定會看到彩虹？",options:["不是，還要角度剛好","是，一定會","只有晚上才會"],answer:0,explanation:"對。不是每次都看得到，還要角度剛好。"},
{question:"彩虹最常在哪種情況比較容易出現？",options:["雨後又有太陽","完全沒有陽光","只有打雷沒有雨"],answer:0,explanation:"沒錯。雨後又有太陽時比較容易看到。"},
{question:"彩虹看起來最像什麼？",options:["彎彎的很多顏色排在一起","一條黑線","一個白色方塊"],answer:0,explanation:"答對了。彩虹最容易看成彎彎的一條很多顏色。"},
{question:"第十六課最重要的重點是什麼？",options:["彩虹需要太陽、小水滴和剛好的角度","只要下雨一定有彩虹","彩虹和陽光沒關係"],answer:0,explanation:"對。這就是本課最重要的重點。"}];
const qp16=document.getElementById("quiz-progress"),qq16=document.getElementById("quiz-question"),qo16=document.getElementById("quiz-options"),qf16=document.getElementById("quiz-feedback"),qn16=document.getElementById("quiz-next");let qi16=0,ql16=false;function renderQuiz16(){const item=quizData16[qi16];ql16=false;qp16.textContent=`第 ${qi16+1} 題，共 ${quizData16.length} 題`;qq16.textContent=item.question;qf16.textContent="";qn16.hidden=true;qo16.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer16(index));qo16.appendChild(button);});}function handleAnswer16(selectedIndex){if(ql16)return;ql16=true;const item=quizData16[qi16];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf16.textContent=item.explanation;qn16.hidden=false;qn16.textContent=qi16===quizData16.length-1?"再玩一次":"下一題 →";}qn16.addEventListener("click",()=>{qi16=qi16===quizData16.length-1?0:qi16+1;renderQuiz16();});setRainbowMode16("sun");renderQuiz16();
