const typhoonModes={whole:{title:"整個颱風",text:"你可以先把颱風想成一個很大、一直轉的風雨圈，中間附近有颱風眼，旁邊是雲雨和大風。",remember:"颱風 = 很大、會旋轉、帶著風和雨的天氣系統。",meter:"100%",label:"很強",eye:1,ring1:1,ring2:1,ring3:1,wind:.7},eye:{title:"颱風眼",text:"颱風眼在中間附近，是颱風很特別的一部分。",remember:"先記住：颱風眼在中間附近。",meter:"42%",label:"中間部位",eye:1,ring1:.22,ring2:.1,ring3:.08,wind:.1},rainband:{title:"旋轉雲雨",text:"一圈一圈轉著的雲和雨，是颱風最明顯的樣子。",remember:"颱風最容易認的樣子，就是一圈一圈在轉。",meter:"82%",label:"很多雲雨",eye:.3,ring1:1,ring2:1,ring3:.78,wind:.26},wind:{title:"大風區",text:"颱風不只會下雨，還會帶來很大的風，所以要特別注意。",remember:"颱風天的大風，是它很重要的一部分。",meter:"96%",label:"很大的風",eye:.18,ring1:.44,ring2:.44,ring3:.3,wind:1}};
const tButtons=document.querySelectorAll(".mode-button"),tTitle=document.getElementById("mode-title"),tText=document.getElementById("mode-text"),tRemember=document.getElementById("mode-remember"),tMeter=document.getElementById("storm-meter"),tLabel=document.getElementById("storm-label"),tEye=document.querySelector(".stage-eye"),tR1=document.querySelector(".stage-ring.one"),tR2=document.querySelector(".stage-ring.two"),tR3=document.querySelector(".stage-ring.three"),tWind=document.querySelector(".stage-wind");
function setTyphoonMode(k){const m=typhoonModes[k];if(!m)return;tButtons.forEach(b=>b.classList.toggle("is-active",b.dataset.mode===k));tTitle.textContent=m.title;tText.textContent=m.text;tRemember.textContent=m.remember;tMeter.style.width=m.meter;tLabel.textContent=m.label;tEye.style.opacity=String(m.eye);tR1.style.opacity=String(m.ring1);tR2.style.opacity=String(m.ring2);tR3.style.opacity=String(m.ring3);tWind.style.opacity=String(m.wind);}
tButtons.forEach(b=>b.addEventListener("click",()=>setTyphoonMode(b.dataset.mode)));
const quizData12=[{question:"颱風最接近下面哪種說法？",options:["很大、會旋轉的風雨系統","一朵普通白雲","只有風沒有雨"],answer:0,explanation:"答對了。颱風可以先這樣理解。"},
{question:"颱風和普通下雨天很不一樣，因為它還有什麼？",options:["很大的風和旋轉","只有比較熱","只有比較亮"],answer:0,explanation:"對。颱風不只是雨，還有很大的風和旋轉。"},
{question:"颱風眼在颱風的哪裡附近？",options:["中間附近","最外面","地面下面"],answer:0,explanation:"沒錯。颱風眼在中間附近。"},
{question:"從上面看颱風，最明顯的樣子是什麼？",options:["一圈一圈在轉","一條直線","完全不動"],answer:0,explanation:"答對了。颱風從上面看會像一圈一圈在轉。"},
{question:"第十二課最重要的重點是什麼？",options:["颱風是很大、會旋轉、帶著風和雨的系統","颱風只是大一點的雲","颱風和風沒有關係"],answer:0,explanation:"對。這就是本課最重要的重點。"}];
const qp12=document.getElementById("quiz-progress"),qq12=document.getElementById("quiz-question"),qo12=document.getElementById("quiz-options"),qf12=document.getElementById("quiz-feedback"),qn12=document.getElementById("quiz-next");let qi12=0,ql12=false;
function renderQuiz12(){const item=quizData12[qi12];ql12=false;qp12.textContent=`第 ${qi12+1} 題，共 ${quizData12.length} 題`;qq12.textContent=item.question;qf12.textContent="";qn12.hidden=true;qo12.innerHTML="";item.options.forEach((option,index)=>{const button=document.createElement("button");button.type="button";button.className="quiz-option";button.textContent=option;button.addEventListener("click",()=>handleAnswer12(index));qo12.appendChild(button);});}
function handleAnswer12(selectedIndex){if(ql12)return;ql12=true;const item=quizData12[qi12];const buttons=[...document.querySelectorAll(".quiz-option")];buttons.forEach((button,index)=>{if(index===item.answer)button.classList.add("is-correct");if(index===selectedIndex&&index!==item.answer)button.classList.add("is-wrong");button.disabled=true;});qf12.textContent=item.explanation;qn12.hidden=false;qn12.textContent=qi12===quizData12.length-1?"再玩一次":"下一題 →";}
qn12.addEventListener("click",()=>{qi12=qi12===quizData12.length-1?0:qi12+1;renderQuiz12();});setTyphoonMode("whole");renderQuiz12();
